### ISSUE TITLE
安装 babel-plugin-zent 后没有起到 按需加载 的作用

### ISSUE THREAD

**Issue by xuehahaha** [youzan/zent#1017]
![default](https://user-images.githubusercontent.com/47238605/52685842-32728580-2f86-11e9-84f8-bbcf18e9f826.png)
如（上图）引用组件后不手动import css的话，组件就没有任何对应样式。

babel-plugin-zent 的配置（下图）
![default](https://user-images.githubusercontent.com/47238605/52686133-58e4f080-2f87-11e9-80d9-cbcb79965ecf.png)

**Comment by cpylua** [comment]
plugins 那个是babel的配置，放到 babelrc 里去，不是 package.json。

**Comment by xuehahaha** [comment]
项目根目录建了一个.babelrc文件，还是不行
![default](https://user-images.githubusercontent.com/47238605/52694435-acb20280-2fa4-11e9-8867-d95e815643cb.png)

**Comment by cpylua** [comment]
你看下你的打包工具有没有正确读到这个配置
