### ISSUE TITLE
Form.d.ts 表单 createForm 类型定义错误

### ISSUE THREAD

**Issue by Yao-JSON** [youzan/zent#1018]
代码 link : https://github.com/youzan/zent/blob/master/packages/zent/typings/libs/Form.d.ts#L53
期望：

```jsx
function createForm(config?: { formValidations?: any }): (component:  React.ComponentClass<IWrappedComponentProps | any> | React.SFC<IWrappedComponentProps | any>) => React.Component<IConnectedFormProps, any>
```

![image](https://user-images.githubusercontent.com/21197611/52930582-f1aeae00-3383-11e9-8569-b5e14043fd37.png)

**Comment by cpylua** [comment]
Fixed in 6.6.2
