### ISSUE TITLE
[bug fix ] Design：图片展示不正确

### ISSUE THREAD

**Issue by macmatilda** [youzan/zent#1032]
"zan-design": "^4.10.4",
    "zent": "^6.6.2"

重现条件：
https://youzan.github.io/zent/zh/component/design

里面的样例代码    Simple.js
图片广告，和样例效果不一致，大图小图没有效果

**Comment by cpylua** [comment]
Close.

1. `zan-design` 从未对外开源，只是 demo 用途。
2. 文档网站的示例和 `zan-design` 无关。
