### ISSUE TITLE
new feature DateRangeQuickPicker组件样式

### ISSUE THREAD

**Issue by watsonhaw** [youzan/zent#1045]
能否修改位element-react那种只需要操作一次的，现在这样需要用户点击两次Input感觉不太方便，只是一个建议。感谢开发者大大。
![image](https://user-images.githubusercontent.com/1267552/55215069-6c949f80-5233-11e9-8c27-1dbaa7e6d407.png)

**Comment by cpylua** [comment]
会考虑的。

我们很老的一个版本就是合在一起的，后来收到反馈用户不会用，就改成分开的了。
