### ISSUE TITLE
Upload 组件当设置maxAmount=1时，设置的默认上传样式trigger={() => ****}会出现input[type=file]原生文件上传按钮的bug？（前提已设置triggerClassName=""）

### ISSUE THREAD

**Issue by lk1583880553** [youzan/zent#1047]
代码如下：
const listUploadProps = {
      type: this.props.type || 'image',//上传文件类型
      tips: this.props.tips || '',//提示
      maxSize: this.props.maxSize || 3 * 1024 * 1024,//默认上传最大size为3M
      maxAmount: this.props.maxAmount || 1,//默认上传最多限制5张
      accept: this.props.accept || 'image/gif,image/jpeg,image/png,image/bmp',//默认支持文件类型
      className: this.props.className || '',//扩展类名
      categoryList: this.props.materialGroupList || '',
      categoryId:this.props.formValues?this.props.formValues.groupId:'',
      localOnly:true,
      // onFetch: (info) => this.updateLocalImage(info),
      onUpload: (info,categoryId) => this.updateLocalImage(info,categoryId),
      triggerClassName: '',
      trigger: () => <Button className='my-custom-upload-button' type='primary'>上传图片</Button>,
      errorMessages: {
        overMaxSize: (data) => `大小超出: ${data.maxSize}!`, // function
        overMaxAmount: (data) => `上传数量超出: ${data.maxAmount}张!`,
        wrongMimeType: false || ((data) => `无法上传${data.type}文件类型，仅支持${this.props.accept}文件类型!`) || '' || (() => false) // show nothing
      }
    };

![image](https://user-images.githubusercontent.com/39514393/55270531-bbe1db00-52da-11e9-80d9-49695b0c4bf3.png)

**Comment by cpylua** [comment]
`Upload` 重写了，API 和交互均有变化。
