### ISSUE TITLE
ts 的头文件 我是服了 在typescript上面一点都不用

### ISSUE THREAD

**Issue by rainbowMorelhahahah** [youzan/zent#1048]
![image](https://user-images.githubusercontent.com/11493796/55275786-2d934680-5326-11e9-89d4-f685f24ede8f.png)

```
 class SKU extends React.Component<ISKUProps, any> {
    static flatten(sku: Array<any>, items: Array<any>, options: {
      optionValue: string
      optionText: string
    }): Array<any>
  }
```

这种地方不应该有默认值嘛？？

**Comment by rainbowMorelhahahah** [comment]
![image](https://user-images.githubusercontent.com/11493796/55275794-5f0c1200-5326-11e9-9704-935004f9edff.png)

**Comment by rainbowMorelhahahah** [comment]
还有sku 组件在 onChange 里面 做 this.setState 操作 会出现 响应巨慢问题

**Comment by cpylua** [comment]
这个组件已经在计划重写了。
