### ISSUE TITLE
Progress组件中AnimatedArc组件常量问题

### ISSUE THREAD

**Issue by sunchenguang** [youzan/zent#1052]
问题： AnimatedArc组件为什么定义`STROKE_OFFSET_RATIO = 0.2` 

我知道这个常量是用来计算此组件白色短圆弧的长度，但是为什么取0.2，是为了让这段圆弧最长不超过第一象限吗？还是别的原因？

看到了这样的注释
```
  // 终点只可能在第一象限(圆形为原点的坐标系)
  // 需要转换成左上角的坐标系内位置
  getArcEndPoint() {

  }

```

**Comment by cpylua** [comment]
就是个样式常量，没什么特殊的地方。0.2是因，那段注释是果。

**Comment by sunchenguang** [comment]
理解。所有0.2是经验得出的值吗

**Comment by cpylua** [comment]
不是经验值，是视觉样式决定的。用来算 mask 长度的，你可以看下代码。
