### ISSUE TITLE
[bug fix]DatePicker: display incorrect

### ISSUE THREAD

**Issue by wangdicoder** [youzan/zent#1053]
Display twice???

<img width="254" alt="Screen Shot 2019-04-15 at 9 45 42 am" src="https://user-images.githubusercontent.com/7374042/56101068-bb487600-5f63-11e9-945c-7fcae40d263b.png">

**Comment by cpylua** [comment]
Please give detailed steps to reproduce it, or something like a codesandbox demo.

**Comment by wangdicoder** [comment]
The [demo](https://youzan.github.io/zent/en/component/datepicker) is showing the bug. 
The bug is displaying in Apr 2019. You can see it if clicking that date picker.

<img width="495" alt="Screen Shot 2019-04-15 at 3 17 38 pm" src="https://user-images.githubusercontent.com/7374042/56108924-b13d6c00-5f91-11e9-9e6d-3585c0161426.png">

**Comment by cpylua** [comment]
Unable to reproduce on my machine. *Please use our github issue template.*

![image](https://user-images.githubusercontent.com/726800/56110516-61f23e00-5f87-11e9-81b4-04e7538cb309.png)

**Comment by wangdicoder** [comment]
**What is the current behavior?**
Here is [sandbox link](https://codesandbox.io/s/pkvqpp01rj). My friend also can reproduce this error on his machine.

**Comment by cpylua** [comment]
![image](https://user-images.githubusercontent.com/726800/56175766-332da380-602b-11e9-98eb-27814f719d84.png)

**Comment by wangdicoder** [comment]
Alright, hopefully someone also meets this situation, which can confirm this issue.

**Comment by cpylua** [comment]
Close.
