### ISSUE TITLE
使用图片导航报dragDropManager

### ISSUE THREAD

**Issue by 459471667** [youzan/zent#1085]
Failed context type: The context `dragDropManager` is marked as required in `DropTarget(DragSource(EditorCardItem))`, but its value is `undefined`.
    in DropTarget(DragSource(EditorCardItem)) (created by EditorCard)

index.js?f788:1 Invariant Violation: Could not find the drag and drop manager in the context of DragSource(EditorCardItem). Make sure to wrap the top-level component of your app with DragDropContext. Read more: http://react-dnd.github.io/react-dnd/docs-troubleshooting.html#could-not-find-the-drag-and-drop-manager-in-the-context

**Comment by cpylua** [comment]
> Make sure to wrap the top-level component of your app with DragDropContext.
