### ISSUE TITLE
[bug fix ]FormDateRangeQuickPickerField : 在快速选择时间范围时,点击范围对应标签没有active样式

### ISSUE THREAD

**Issue by hanlu12123** [youzan/zent#1179]
![image](https://user-images.githubusercontent.com/25897918/65128898-e4969200-da2c-11e9-9f10-b8fdd1b16286.png)
如上图, 选择了近30天, 但'近30天'的标签没有高亮, 看了下应该是在form中的field的handleChange做了一层处理有问题,希望尽快修复下

**Comment by intellild** [comment]
#1181
