### ISSUE TITLE
Form 组件 API 文档是不是不见了

### ISSUE THREAD

**Issue by FishPlusOrange** [youzan/zent#1240]
地址：

https://youzan.github.io/zent/zh/component/form

见截图：

![Form 组件 API 文档是不是不见了](https://user-images.githubusercontent.com/22132265/68590077-9fd92580-04c8-11ea-8bf6-5c7a2792594a.png)

**Comment by cpylua** [comment]
API 在这里有链接，不再人工维护表格，按组件名/函数名搜索即可。https://youzan.github.io/zent/zh/component/form#api
