### ISSUE TITLE
Form: 由6.x升级为7.3.1之后，@zent/compat导入的Form无样式

### ISSUE THREAD

**Issue by herman7** [youzan/zent#1276]
描述：
按照升级文档，将zent由6.x升级为7.3.1，babel-plugin-zent也升级到2.2.2，
由于Form的breaking change，故安装@zent/compat使用旧版本的From，然而旧版本Form的样式没有自动引入，布局会变化。
比如下面的`horizontal`的`.zent-form--horizontal`就不会被引入
`import { Form } from '@zent/compat'`
`<Form horizontal onSubmit={() => {}}>`

问题：
请问我想使用@zent/compat的From，我还需要配置什么么？

**Comment by cpylua** [comment]
@zent/compat 也要配 babel 插件，看下readme，
https://github.com/zent-contrib/zent-compat

**Comment by herman7** [comment]
感谢，已配置，不过添加配置后，
使用方式：
`import { Form } from '@zent/compat'`
`const { FormSelectField, FormInputField, FormDateRangeQuickPickerField, createForm } = Form`

问题：
FormSelectField，FormInputField等表单组件的样式会被注入，类似类名为`.zent-select[data-zv="7.3.1"]`等。
而`DateRangeQuickPicke`的类似类名为`.zent-datetime-picker[data-zv="7.3.1"]`的样式没有被注入，导致样式错乱，怀疑是babel没有把它的样式打包进去。
此时如果刻意引入一下新版本zent的`DateRangeQuickPicker`组件，样式就会被babel打包进来。

version:
zent: 7.3.1
babel-plugin-zen: 2.2.2
@zent/compat: 1.0.3

**Comment by herman7** [comment]
尝试建立了一个新的测试项目，验证发现并没有上面的问题。
所以应该是原项目中样式被其他位置影响到了。
我再自己找找原因吧。

感谢。

**Comment by herman7** [comment]
未找到直接问题及解决办法，临时全局引入zent/css/index.css，Form迁移完成后再去掉吧..

**Comment by cpylua** [comment]
试一下 1.0.4
