### ISSUE TITLE
select 下拉弹层渲染节点如何固定在触发器的父元素中

### ISSUE THREAD

**Issue by fizz1992** [youzan/zent#1291]
select 下拉弹层渲染节点如何固定在触发器的父元素中。弹出层中设置select下拉会导致选项与选框奇异分离的现象。

**Comment by cpylua** [comment]
分离的现象能给个 codesandbox.io 的 demo 吗？

**Comment by fizz1992** [comment]
项目使用版本zent": "^6.6.5"。
最新的版本已经修复了这个问题。新项目会尝试使用最新版本。☆⌒(*＾-゜)v

**Comment by cpylua** [comment]
先关了。

还有问题的话可以重新开个 issue，下次记得放上重现问题的 demo 链接。
