### ISSUE TITLE
该组件库的css命名规范是什么?

### ISSUE THREAD

**Issue by JoMartinezZhu** [youzan/zent#1292]
## 该组件库的css命名规则是什么?

---

在学习搭建自家的组件库，针对 css 命名这个规范有点疑惑？

**Comment by cpylua** [comment]
1. `zent-` 开头，作为组件库的 namespace；后面接组件名作为组件内的小 namespace。
2. 类 [BEM](http://getbem.com/introduction/)，但是没有强制，个人对这个不是很感冒。
