### ISSUE TITLE
官方文档Design部分有示例代码或者哪里有Demo吗？现在Preview和Editor部分无法运行。

### ISSUE THREAD

**Issue by helloworldchao** [youzan/zent#1299]
官方文档Design部分有示例代码或者哪里有Demo吗？现在Preview和Editor部分按照文档的示例设置之后无法使用，只能显示下图的部分
![image](https://user-images.githubusercontent.com/8320377/70960662-9b50ef80-20ba-11ea-8926-6aa5a09ee627.png)

**Comment by cpylua** [comment]
该组件已废弃。demo 可以参考https://github.com/zent-contrib/design/
