### ISSUE TITLE
a problem with cloneElement directly modifying the child components passed into Swiper to modify child's style attribute.

### ISSUE THREAD

**Issue by MashiroWang** [youzan/zent#1301]
**Do you want to request a *feature* or report a *bug*?**
When pass a custom react component (not a HTMLElement) into Swiper，float and height doesn't apply to child elements because of style is not custom component's property.

I think it is possible to wrap each item of the children using a wrapper div，and modify height & width & float on it.

**What is the current behavior?**
When pass list of custom component into Swiper, it doesn't make sense.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io or similar.**

**What is the expected behavior?**
make sense.

**Which versions of Zent and React, and which browser / OS are affected by this issue? Did this work in previous versions of Zent?**
7.4.2

**Comment by cpylua** [comment]
1. 自己包一层

or

2. 透传 `style` 到下层节点
