### ISSUE TITLE
FormSelectField传入data数组无法显示?

### ISSUE THREAD

**Issue by helloworldchao** [youzan/zent#1313]
在使用umi框架时，在开发状态下没有问题，打包之后就出现了这个问题。

**Comment by helloworldchao** [comment]
使用create-react-app创建一个全新的应用，然后将App.js文件的内容替换为

`
import React from 'react';
import {
  Form,
  FormStrategy,
  FormSelectField,
  FormNumberInputField,
} from 'zent';

import 'zent/css/index.css';

export default () => {
  const form = Form.useForm(FormStrategy.View);
  return (
    <Form layout="horizontal" form={form}>
      <FormSelectField
        name="type"
        label="类型:"
        defaultValue={'1'}
        data={[
          { value: '1', text: '普通用户' },
          { value: '2', text: '高级用户' },
        ]}
        required
      />
      <FormNumberInputField
        name="age"
        label="年龄:"
        defaultValue={12}
        props={{
          showStepper: true,
        }}
      />
    </Form>
  );
}
`
则不管是开发状态还是打包后Select的内容都无法显示。
使用umi框架时开发状态正常，打包状态异常。

**Comment by cpylua** [comment]
`data` 放 `props`

https://codesandbox.io/s/epic-leftpad-wwmhq
