### ISSUE TITLE
请问如何实时获取form值？？

### ISSUE THREAD

**Issue by shenhaihua** [youzan/zent#1314]
请问如何实时获取form值？？

**Comment by cpylua** [comment]
不提供获取整个 `Form` 所有值的能力，会被滥用。

获取表单域的值可以参考这个例子：https://youzan.github.io/zent/zh/component/form#du-qu-biao-dan-zhi。
后面会把 `useFieldValue` 暴露出来，同时使用多个域值写起来会舒服一些，不需要套多层组件。#1315
