### ISSUE TITLE
FormDateRangeQuickPickerField组件是否支持创建时默认高亮某个preset的对象

### ISSUE THREAD

**Issue by helloworldchao** [youzan/zent#1330]
FormDateRangeQuickPickerField组件是否支持创建时默认高亮某个preset的对象？看了文档尝试了defaultValue和props中的chooseDays都无法在创建时默认高亮某个preset的对象

**Comment by cpylua** [comment]
`preset` 现在都是类似快捷键的作用，它们的意义也是相对时间，比如今天选了‘最近7天’，到了明天就不是了‘最近7天’了，所以做成了不受控的。

不过如果 `value` 不存在，可以考虑加个选项默认选中一个 `preset`，但注意这仍然不是受控的，只是初始化的时候根据当前时间默认选了一个时间段。我猜这是你想要的效果？

**Comment by helloworldchao** [comment]
> `preset` 现在都是类似快捷键的作用，它们的意义也是相对时间，比如今天选了‘最近7天’，到了明天就不是了‘最近7天’了，所以做成了不受控的。
> 
> 不过如果 `value` 不存在，可以考虑加个选项默认选中一个 `preset`，但注意这仍然不是受控的，只是初始化的时候根据当前时间默认选了一个时间段。我猜这是你想要的效果？

是的，是这个意思。你指的value是defaultValue吗？
