### ISSUE TITLE
跪求指导～微页面编辑里面的富文本图片上传功能window.__ueditor_后面是什么？？

### ISSUE THREAD

**Issue by shenhaihua** [youzan/zent#1359]
####  跪求指导～

![image](https://user-images.githubusercontent.com/6947259/75174276-4640f200-576b-11ea-9f05-88e442ce5c73.png)

项目中需要使用微页面编辑里面的富文本图片上传功能，参考demo在editor/plugins/index.js中，试过window.__ueditor_simpleupload、window.__ueditor_image、window.__ueditor_upload，均无反应，也没有报错。。。

请问这里是什么？或者说应该怎么做？？
谢谢～

**Comment by cpylua** [comment]
ueditor 的定制请参考 ueditor 文档。

你列的那些变量不是 ueditor 的 API，demo 里使用的 ueditor 代码是定制过的。

**Comment by cpylua** [comment]
I’m closing this issue because it's not an issue of this project.
