### ISSUE TITLE
在类组件中使用from组件

### ISSUE THREAD

**Issue by liyuewen** [youzan/zent#1379]
我希望在类组件中使用某些组件比如from组件但是他报了错误
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
我看文档https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react发现是不要在类组件中调用挂钩。请问有解决的方法么

**Comment by wjw99830** [comment]
```tsx
funciton MyForm({ children, ...props }) {
  const form = Form.useForm(FormStrategy.View);

  return (
    <Form {...props} form={form}>
      {children(form)}
    </Form>
  );
}

class MyComponent extends Component {
  onSubmit(form) {
    const formValue = form.getValue();
    // do sth.
  }

  render() {
    return (
      <MyForm
        onSubmit={this.onSubmit}
      >
        {form => <Button onClick={() => form.submit()}>Submit</Button>}
      </MyForm>
    }
}
```
