### ISSUE TITLE
zent-kit: command not found是什么问题

### ISSUE THREAD

**Issue by fekata** [youzan/zent#139]
我执行的顺序是这样的：
$ git clone https://github.com/youzan/zent.git
$ cnpm install zent --save
cd zent/
$ npm test
然后就报错了：
> ./scripts/run-tests.sh
./scripts/run-tests.sh: line 6: zent-kit: command not found
npm ERR! Test failed.  See above for more details.

**Comment by lama-pacos** [comment]
需要安装 zent-kit 

npm install zent-kit -g
