### ISSUE TITLE
在nextjs中按需导入组件出错

### ISSUE THREAD

**Issue by ecpanda** [youzan/zent#1396]
`
//.babelrc
{
  "presets": ["next/babel"],
  "plugins": [
      ["zent"]
  ]
}
`
`
//packagge.json
{
  "name": "inext",
  "version": "0.1.0",
  "description": "Fancy Next.js app",
  "scripts": {
    "dev": "next",
    "build": "next build && next export",
    "start": "next start",
    "build:static": "next build && next out"
  },
  "dependencies": {
    "antd": "^4.2.5",
    "next": "^9.4.3-canary.0",
    "normalize.css": "^8.0.1",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "sass": "^1.26.5",
    "zent": "^7.4.4"
  },
  "devDependencies": {
    "babel-plugin-import": "^1.13.0",
    "babel-plugin-zent": "^2.2.2"
  }
}
`

**报错：**
`
Server Error
SyntaxError: Unexpected identifier

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///Users/jackyin/ownproject/inext/node_modules/zent/es/preview-image/index.js (1)
Module._compile
internal/modules/cjs/loader.js (721:23)
Object.Module._extensions..js
internal/modules/cjs/loader.js (787:10)
Module.load
internal/modules/cjs/loader.js (653:32)
tryModuleLoad
internal/modules/cjs/loader.js (593:12)
Function.Module._load
internal/modules/cjs/loader.js (585:3)
Module.require
internal/modules/cjs/loader.js (690:17)
require
internal/modules/cjs/helpers.js (25:18)
eval
external%20%22zent/es/preview-image/index.js%22 (1:0)
Object.zent/es/preview-image/index.js
file:///Users/jackyin/ownproject/inext/.next/server/static/development/pages/index.js (333:1)
__webpack_require__
file:///Users/jackyin/ownproject/inext/.next/server/static/development/pages/index.js (23:31)
eval
webpack-internal:///./common/components/carousel/CarouselPreviewImages.js (10:88)
Module../common/components/carousel/CarouselPreviewImages.js
file:///Users/jackyin/ownproject/inext/.next/server/static/development/pages/index.js (104:1)
__webpack_require__
file:///Users/jackyin/ownproject/inext/.next/server/static/development/pages/index.js (23:31)
eval
webpack-internal:///./common/components/project/components/ProjectExperienceItem.js (6:107)
Module../common/components/project/components/ProjectExperienceItem.js
file:///Users/jackyin/ownproject/inext/.next/server/static/development/pages/index.js (231:1)
__webpack_require__
file:///Users/jackyin/ownproject/inext/.next/server/static/development/pages/index.js (23:31)
`

**Comment by cpylua** [comment]
给一个可以重现问题的 codesandbox demo

**Comment by wjw99830** [comment]
```js
// next.config.js
const withTM = require('next-transpile-modules')(['zent']);
module.exports = withTM;
```

请移步next.js issues [next.js #706](https://github.com/vercel/next.js/issues/706#issuecomment-585058545)

**Comment by ecpanda** [comment]
@wjw99830

**Comment by ecpanda** [comment]
> ```js
> // next.config.js
> const withTM = require('next-transpile-modules')(['zent']);
> module.exports = withTM;
> ```
> 
> 请移步next.js issues[#706](https://github.com/vercel/next.js/issues/706#issuecomment-585058545)

竟然发了中文，哈哈哈，搞错了，想不到还有中文回复。

谢谢wjw99830,cpylua

**Comment by ecpanda** [comment]
> ```js
> // next.config.js
> const withTM = require('next-transpile-modules')(['zent']);
> module.exports = withTM;
> ```
> 
> 请移步next.js issues[#706](https://github.com/vercel/next.js/issues/706#issuecomment-585058545)

好的，我试下子，thx
