### ISSUE TITLE
vant非常棒，但它是vue组件库，请问zent有计划出一个移动端react版本吗？

### ISSUE THREAD

**Issue by H-Sven** [youzan/zent#1408]
vant在Vue生态下非常好用，我所有的Vue移动端项目都是使用的vant

但是最近在使用react技术栈，但是react在移动端的UI库只有antd-mobile, 但是感觉并不是特别好用，而且更新也不是特别及时。

请问youzan有计划出一个基于react的移动端UI库吗？

**Comment by cpylua** [comment]
暂时没有计划。

有赞移动端用的 Vue，没有使用场景。
