### ISSUE TITLE
Slider组件点击滑块边缘会导致滑块滑动到范围外

### ISSUE THREAD

**Issue by dislido** [youzan/zent#1461]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
在滑块滑到最左侧后，再点击滑块左侧，会导致onChange值变为小于min，并报错Error: value must between min and max when `range` is false; 最大值侧也有同样问题
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io or similar.**
[![Edit optimistic-tu-e1kd6](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/optimistic-tu-e1kd6?fontsize=14&hidenavigation=1&theme=dark)
**What is the expected behavior?**

**Which versions of Zent and React, and which browser / OS are affected by this issue? Did this work in previous versions of Zent?**
react@16.12.0, chrome84
zent@7.0.0, 7.4.4, 8.0.0, 8.4.0, 8.5.5
zent@6.5.5正常

**Comment by cpylua** [comment]
> 在滑块滑到最左侧后，再点击滑块左侧，会导致onChange值变为小于min，并报错Error: value must between min and max when range is false; 最大值侧也有同样问题

用文档里的示例没有重现你说的问题，请给一个能重现问题的 codesanbox 链接。
