### ISSUE TITLE
Pop组件在trigger='none'时，visible也变成了必传参数

### ISSUE THREAD

**Issue by dislido** [youzan/zent#1483]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
当Pop当trigger参数值为'none'时，如果没有传visible，就会报错：visible and onVisibleChange must be used together

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io or similar.**
[![Edit happy-rgb-4jvww](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-rgb-4jvww?fontsize=14&hidenavigation=1&theme=dark)
**What is the expected behavior?**
trigger为none时，不必需手动维护visible，表现为visible=false一样
**Which versions of Zent and React, and which browser / OS are affected by this issue? Did this work in previous versions of Zent?**
react@16.12.0
zent@8.4.0,8.5.8

**Comment by cpylua** [comment]
That is the expected behavior.

`Pop` is a [controlled component](https://reactjs.org/docs/forms.html#controlled-components) when trigger is `none`.
