### ISSUE TITLE
Bug(Input): it don't trigger autosize when set input value asynchronously

### ISSUE THREAD

**Issue by love2me** [youzan/zent#1494]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
not trigger autosize event and not have scroller bar

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io or similar.**
https://codesandbox.io/s/serene-faraday-we0b0

**What is the expected behavior?**
the input will autosize after i set value

**Which versions of Zent and React, and which browser / OS are affected by this issue? Did this work in previous versions of Zent?**
react: 16.13.1
zent: 8.5.8

**Comment by cpylua** [comment]
`autosize` only handles keyboard and window resize events, a manual `update()` is required to handle `value` prop change.
http://www.jacklmoore.com/autosize/
