### ISSUE TITLE
select Popup 字符过长时 定位有问题

### ISSUE THREAD

**Issue by jacksirens** [youzan/zent#1534]
[QQ20201111-174808-HD.mp4.zip](https://github.com/youzan/zent/files/5523308/QQ20201111-174808-HD.mp4.zip)
怀疑是option 文本过长导致

**Comment by cpylua** [comment]
是不是用了 `autoWidth`? 给个 codesandbox demo

**Comment by cpylua** [comment]
Close, no response.
