### ISSUE TITLE
ClampLines展示emoji错误；某些宽度下没有正确折叠

### ISSUE THREAD

**Issue by dislido** [youzan/zent#1581]
---

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
1.ClampLines在折叠处遇到length>=2的字符时，会将该字符截断导致展示错误字符
2.在特定宽度下没有正确折叠导致换行
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io or similar.**
[![Edit happy-nightingale-7i1b4](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-nightingale-7i1b4?fontsize=14&hidenavigation=1&theme=dark)
**What is the expected behavior?**

**Which versions of Zent and React, and which browser / OS are affected by this issue? Did this work in previous versions of Zent?**
zent@9.0.0-beta19, react@17.0.0, macOS 11.0.1, chrome 86

**Comment by cpylua** [comment]
String iteration should be done on character level. `str.length !== numberOfCharacters(str)`
