### ISSUE TITLE
Select 支持设置多选数量上限

### ISSUE THREAD

**Issue by kainstar** [youzan/zent#1620]
在使用多选选择的场景中，限制用户的选择数量上限是一个常见的需求，目前 zent 的多选没有支持这类功能的参数，若自己实现则使用时需要在 onChange 中根据 items 数量执行不同的逻辑，而且需要在用户选择到数量上限后更新所有未选中的 options 的 disabled 属性为 true，比较麻烦。

功能期望描述：通过一个属性设置最多可选的选项数量，在选择到数量上限的情况下，所有未选中的选项会展示为 disabled 的样式，且点击这些选项不会触发 onChange

**Comment by cpylua** [comment]
通过 `options` 控制。
