### ISSUE TITLE
日期控件设置了最小日期后，居然连本年度都无法选中。比如设置disableDate={{min:2020-02-02}}, 年度选择里连2020都被禁用

### ISSUE THREAD

**Issue by bolerole** [youzan/zent#1636]
## [提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

---

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io or similar.**

**What is the expected behavior?**

**Which versions of Zent and React, and which browser / OS are affected by this issue? Did this work in previous versions of Zent?**

**Comment by cythiaY** [comment]
感谢反馈，我们会尽快修复该问题
