### ISSUE TITLE
日期控件偶现问题，出现“18岁”文案

### ISSUE THREAD

**Issue by bolerole** [youzan/zent#1637]
![Lark20210111-115741](https://user-images.githubusercontent.com/24889681/104146049-476f2200-5404-11eb-859e-d4d5ce20fd72.png)

**Comment by cpylua** [comment]
代码里都没这个字…

检查下你本地环境，有没有脚本作了什么劫持，确认有问题的话给个能复现的codesanbox链接

**Comment by cpylua** [comment]
没有回复，先关了。

**Comment by unStone** [comment]
意外发现重现步骤，不是bug：
1. 打开带有日期选择器的页面
2. 右键选择"翻译成中文"
3. 点开日期选择期就会出现这种现象
![image](https://user-images.githubusercontent.com/20199768/107003794-4f826d80-67c8-11eb-8362-3fd8b58f10e8.png)
