### ISSUE TITLE
circular reference in zent

### ISSUE THREAD

**Issue by AsukaSong** [youzan/zent#1687]
```typescript
// form/formulr/models/basic.ts
import {
  ErrorSubscriber,
  IMaybeError,
  IValidation,
  IValidators,
  validate,
  ValidateOption,
} from '../validate';
```

```typescript
// form/formulr/validate.ts
import { BasicModel, isFieldSetModel } from './models';
```

```typescript
// form/formulr/models/index.ts
export * from './basic';
```

Also found in other files in `form/formulr/models/` that import `form/formulr/validate.ts` and `form/formulr/models/basic.ts`

Circular reference will cause `BasicModel` initializes to `undefined`, other models that extend `BasicModel` may throw an error sometimes

## minimal reproduction

```bash
yarn init
yarn add react react-dom zent
yarn add webpack@5 webpack-cli 
```

`index.js`
```javascript
import { FieldArrayModel } from 'zent'
console.log(FieldArrayModel)
```

`index.html`
```html
<!DOCTYPE html>
<html>
    <body>
        <script src="/dist/main.js"></script>
    </body>
<html>
```

```bash
yarn run webpack --mode production --entry ./index.js
npx http-server
```

then open `localhost:8080`

### expected behavior

`FieldArrayModel` logged

### actual behavior

```
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at s (main.js:2)
    at main.js:2
    at main.js:2
    at main.js:2
    at main.js:2
```

- only happens in production mode
- only happens when build with `webpack@5`

**Comment by cpylua** [comment]
- [ ]  alert/Alert.tsx > alert/components/AlertItem.tsx
- [ ]  date-picker/utils/index.ts > date-picker/utils/getValueInRangePicker.ts
- [ ]  date-picker/utils/index.ts > date-picker/utils/getValueInSinglePicker.ts
- [ ]  date-picker/panels/date-panel/index.tsx > date-picker/panels/date-panel/DateFooter.tsx
- [ ]  dialog/Dialog.tsx > dialog/open.tsx
- [ ]  popover/Context.tsx > popover/Popover.tsx > popover/Anchor.tsx
- [ ]  popover/Content.tsx > popover/Context.tsx > popover/Popover.tsx
- [ ]  popover/Context.tsx > popover/Popover.tsx
- [ ]  popover/Context.tsx > popover/Popover.tsx > popover/withPopover.tsx
- [ ]  popover/Popover.tsx > popover/withPopover.tsx
- [ ]  error-boundary/ErrorBoundary.tsx > error-boundary/catchError.tsx
- [ ]  error-boundary/ErrorBoundary.tsx > error-boundary/withErrorBoundary.tsx
- [ ]  form/formulr/models/base.ts > form/formulr/models/form.ts > form/formulr/models/set.ts
- [ ]  form/formulr/models/base.ts > form/formulr/models/form.ts > form/formulr/models/set.ts > form/formulr/models/basic.ts
- [ ]  grid/BatchComponents.tsx > grid/utils.ts > grid/Grid.tsx
- [ ]  grid/Grid.tsx > grid/Body.tsx > grid/ColGroup.tsx
- [ ]  grid/utils.ts > grid/Grid.tsx > grid/Body.tsx > grid/ColGroup.tsx
- [ ]  grid/Grid.tsx > grid/Body.tsx
- [ ]  grid/Grid.tsx > grid/Body.tsx > grid/Row.tsx > grid/Cell.tsx
- [ ]  grid/Grid.tsx > grid/Body.tsx > grid/Row.tsx
- [ ]  grid/Grid.tsx > grid/Header.tsx
- [ ]  grid/utils.ts > grid/Grid.tsx
- [ ]  mention/Mention.tsx > mention/position.ts
- [ ]  notice/Container.tsx > notice/Wrap.tsx
- [ ]  number-input/NumberInput.tsx > number-input/decimal.ts
- [ ]  number-input/NumberInput.tsx > number-input/integer.ts
- [ ]  pop/Action.tsx > pop/Pop.tsx
- [ ]  portal/PurePortal.tsx > portal/context.ts
- [ ]  radio/AbstractRadio.tsx > radio/GroupContext.tsx
- [ ]  select/Option.tsx > select/Select.tsx
- [ ]  select/Select.tsx > select/TagList.tsx
- [ ]  select/Select.tsx > select/TagList.tsx > select/Tag.tsx
- [ ]  select/Select.tsx > select/reviver.ts
- [ ]  steps/Steps.tsx > steps/components/BreadcrumbSteps.tsx
- [ ]  steps/Steps.tsx > steps/components/NumberSteps.tsx

![circular](https://user-images.githubusercontent.com/726800/114532075-0eeb1880-9c7f-11eb-9ff6-27f0ab7d0535.png)

**Comment by cpylua** [comment]
这个没那么紧急，我们目前的打包方案下是没有问题的。

**Comment by AsukaSong** [comment]
不知道为什么我这里也好了，那先 close 了，有需要再 reopen
