### ISSUE TITLE
zent-form: 'warning: unknown props' with react v15.4.2; warning with extral input;

### ISSUE THREAD

**Issue by LucasIcarus** [youzan/zent#17]
1. unknown props
![1](http://youzan-fancy.oss-cn-shanghai.aliyuncs.com/zent-issues/zent-form.png)

2. example: overview, 在使用目前 react 版本也会出现.
当额外信息input有输入时.
![2](http://youzan-fancy.oss-cn-shanghai.aliyuncs.com/zent-issues/zent-form-extral.png)

**Comment by cpylua** [comment]
fixed
