### ISSUE TITLE
zent9-Collapse 折叠面板

### ISSUE THREAD

**Issue by fufangcaoshanhu** [youzan/zent#1701]
**Do you want to request a *feature* or report a *bug*?**
Collpase.Panel的一个属性名称为key，会导致列表渲染的时候一直会报一个警告，而且感觉图标支持自定义会更好点

**What is the current behavior?**
Collpase.Panel的一个属性名称为key，会导致列表渲染的时候一直会报一个警告

**What is the expected behavior?**
1、Collpase.Panel的一个属性名称最好不要为key
2、图标支持自定义
**Which versions of Zent and React, and which browser / OS are affected by this issue? Did this work in previous versions of Zent?**
9.5.0

**Comment by cpylua** [comment]
1. 这个  `key` 就是 [React 组件上的 `key`](https://reactjs.org/docs/lists-and-keys.html#keys)，不是 props 上的。看了下 demo 里没有警告，请提供可以重现问题的 [codesandbox](https://codesandbox.io) 链接。
2. 设计如此，暂时没有计划支持。

**Comment by cpylua** [comment]
没有回复，先关了。
