### ISSUE TITLE
pop 通过hover打开，当页面滚动，pop不关闭

### ISSUE THREAD

**Issue by qld-cf** [youzan/zent#1777]
![trump.jpg](https://cdn.nlark.com/yuque/0/2021/png/2166813/1630310842100-59b1c2ab-95bb-450e-9715-4d4181cded1e.png?x-oss-process=image%2Fresize%2Cw_750%2Climit_0)

zent/compat 好像尝试修复过，看了源码, 旧版compact和新zent，默认quirk是开启的，但是现在还是没用，pop经过滚动不会消失

https://github.com/youzan/zent/issues/340

https://github.com/youzan/zent/commit/61831c96061df4c47621a9c32350f1558e59339e

**Comment by cpylua** [comment]
没看懂，你说的到底是 `@zent/compat` 里的 `Pop` 有问题还是 `zent` 里的 `Pop` 有问题？

**Comment by qld-cf** [comment]
> 没看懂，你说的到底是 `@zent/compat` 里的 `Pop` 有问题还是 `zent` 里的 `Pop` 有问题？

@zent/compat

**Comment by cpylua** [comment]
`quirk` 默认是 `false`，文档里写错了。

**Comment by cpylua** [comment]
#340 里面修复的不是你说的这个问题，它指的是早期版本 `Pop`  鼠标滚动之后再也无法关闭弹层。你这里描述的问题是在滚动过程中以及滚动完成后，不移动鼠标的情况下无法关闭的问题。

针对这个问题，`@zent/compat` 里的 `Pop` 由于内部实现监听的事件问题是无解的。

新版 `zent` 里 `Pop` 组件换了实现方式，可以实现滚动停止后，不移动鼠标的情况下自动关闭，但是在滚动过程也不会关闭。

所以，建议你换新版 `zent` 里的 `Pop`，`@zent/compat` 里面的组件仅是为了方便迁移老代码而存在的，不会迭代里面的功能。

**Comment by qld-cf** [comment]
> #340 里面修复的不是你说的这个问题，它指的是早期版本 `Pop` 鼠标滚动之后再也无法关闭弹层。你这里描述的问题是在滚动过程中以及滚动完成后，不移动鼠标的情况下无法关闭的问题。
> 
> 针对这个问题，`@zent/compat` 里的 `Pop` 由于内部实现监听的事件问题是无解的。
> 
> 新版 `zent` 里 `Pop` 组件换了实现方式，可以实现滚动停止后，不移动鼠标的情况下自动关闭，但是在滚动过程也不会关闭。
> 
> 所以，建议你换新版 `zent` 里的 `Pop`，`@zent/compat` 里面的组件仅是为了方便迁移老代码而存在的，不会迭代里面的功能。

好的，感谢
