### ISSUE TITLE
必填表单项允许只填一个空格

### ISSUE THREAD

**Issue by MichaelYuhe** [youzan/zent#1875]
感觉是不是要对输入进行trim的操作再判空比较合理呢？

**Comment by cpylua** [comment]
加个 validator 校验一下就行了。

**Comment by wjw99830** [comment]
如果业务上有比较多这样的场景，建议基于Form基础组件封装业务通用的组件

**Comment by MichaelYuhe** [comment]
> 加个 validator 校验一下就行了。

好的，我也是这么做的，只是个人认为这么设计或者直接加个选项可能合理一些，所以提出一个建议。谢谢解答
