### ISSUE TITLE
Grid 组件的expandatio属性，能支持无子数据时不展示折叠图标吗

### ISSUE THREAD

**Issue by wanpan11** [youzan/zent#1895]
![image](https://user-images.githubusercontent.com/38714194/149702070-4ba283b4-2d31-492e-8a3f-3b20f2f3dd47.png)
现在好像 是直接添加了一项 默认都会有这个图标
![image](https://user-images.githubusercontent.com/38714194/149703279-a7bf90c2-d169-4fb4-9f5c-ff144cd9d464.png)
😁

**Comment by w91** [comment]
![image](https://user-images.githubusercontent.com/2599455/149722883-ebb149dc-55ed-4256-b8c4-c634934a0be9.png)
可以看下示例，需要加一下 isExpanded 的规则逻辑

**Comment by wanpan11** [comment]
> ![image](https://user-images.githubusercontent.com/2599455/149722883-ebb149dc-55ed-4256-b8c4-c634934a0be9.png) 可以看下示例，需要加一下 isExpanded 的规则逻辑

isExpanded 这个属性好像是 控制默认展不展看开的
![image](https://user-images.githubusercontent.com/38714194/149727198-2658c1cf-fea1-4e22-8e7b-eb5cbf1797b0.png)

我试的 好像不能去掉空子集 前面的icon
![image](https://user-images.githubusercontent.com/38714194/149727520-4a1d7911-b381-492b-a90c-b3ef5f00916f.png)
=、=

**Comment by w91** [comment]
> > ![image](https://user-images.githubusercontent.com/2599455/149722883-ebb149dc-55ed-4256-b8c4-c634934a0be9.png) 可以看下示例，需要加一下 isExpanded 的规则逻辑
> 
> isExpanded 这个属性好像是 控制默认展不展看开的 ![image](https://user-images.githubusercontent.com/38714194/149727198-2658c1cf-fea1-4e22-8e7b-eb5cbf1797b0.png)
> 
> 我试的 好像不能去掉空子集 前面的icon ![image](https://user-images.githubusercontent.com/38714194/149727520-4a1d7911-b381-492b-a90c-b3ef5f00916f.png) =、=

确实，不好意思前面理解错了，这个需要后面加个参数支持一下

**Comment by wanpan11** [comment]
好的 感谢大佬回复 😁😄😄
