### ISSUE TITLE
form 表单样式难以调整 超出父级宽度不能进行换行

### ISSUE THREAD

**Issue by Hello-job** [youzan/zent#1897]
## [提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

---

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io or similar.**

**What is the expected behavior?**

**Which versions of Zent and React, and which browser / OS are affected by this issue? Did this work in previous versions of Zent?**

**Comment by w91** [comment]
麻烦再具体描述一下问题，贴一下代码片段/截图之类的
