### ISSUE TITLE
form如何回显数据

### ISSUE THREAD

**Issue by csywweb** [youzan/zent#1944]
React: 17.0.2
zent: 9.12.7

新版本表单再view模式下如何回显数据，旧版本的value用不了，

**Comment by CFDylan** [comment]
1. 旧版本，是指哪个版本？
2. 提供下，9.12.7 版本，能复现这个问题的代码片段

**Comment by cpylua** [comment]
文档里有示例 https://youzan.github.io/zent/zh/component/form#du-qu-ding-yue-biao-dan-zhi

**Comment by cpylua** [comment]
先关了，还有疑问请重新提 issue。
