### ISSUE TITLE
React hot reload in docs

### ISSUE THREAD

**Issue by cpylua** [youzan/zent#205]
Component level hot reload is not that easy. 
Each page is compiled from a Markdown file on the fly.
The layout is written in Vue.

- [x] Replace Vue with React in site
- [x] Remove all Vue related config in webpack config
- [x] Add [react-hot-loader](https://github.com/gaearon/react-hot-loader)

**Comment by cpylua** [comment]
Component level hot reload is not that easy. 
Each page is compiled from a Markdown file on the fly.
The layout is written in Vue.

What the f**k!

**Comment by LucasIcarus** [comment]
#224 in progress

**Comment by LucasIcarus** [comment]
migrate to #229
