### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by cpylua** [youzan/zent#206]
Translate Chinese documentations to English.

Need your help!

**Comment by axuebin** [comment]
Can I participate in the translation?

I want to try.

**Comment by cpylua** [comment]
当然可以。

需要做的事情可能包括：

- [ ] 网站上需要提供一个中英文切换的入口，可以考虑放在顶部。这里会涉及到一些文档网站的一些改造。
- [ ] 翻译组件文档。

需要帮助的话可以细聊。

**Comment by axuebin** [comment]
如果可以 那我试试~
