### ISSUE TITLE
zent-select: 'warning: unknown props' with react v15.4.2 and others..

### ISSUE THREAD

**Issue by LucasIcarus** [youzan/zent#21]
1. unknown props

![1](http://youzan-fancy.oss-cn-shanghai.aliyuncs.com/zent-issues/zent-select-up.png)

2. 外部清空选择之后应恢复显示placeholder

![2](http://youzan-fancy.oss-cn-shanghai.aliyuncs.com/zent-issues/zent-select-clear.gif)

3. disabled 需要增加指针样式

![3](http://youzan-fancy.oss-cn-shanghai.aliyuncs.com/zent-issues/zent-select-dis.gif)

4. search 输入是否在一次 pop 开闭之后仍然保留, 如果保留是否应该加一个清空按钮.

![4](http://youzan-fancy.oss-cn-shanghai.aliyuncs.com/zent-issues/zent-select-sea.gif)

5. tag上的删除按钮, 在点击事件是否冒泡上表现不一致.

![5-1](http://youzan-fancy.oss-cn-shanghai.aliyuncs.com/zent-issues/zent-select-tag-1.gif)

![5-2](http://youzan-fancy.oss-cn-shanghai.aliyuncs.com/zent-issues/zent-select-tag-2.gif)

**Comment by LucasIcarus** [comment]
#43 进行了对兼容性错误的初步修正..

**Comment by cpylua** [comment]
NO.1 is fixed

**Comment by cpylua** [comment]
Close, tracking in another issue
