### ISSUE TITLE
zent-table: example: selection.. disabled 样式问题

### ISSUE THREAD

**Issue by LucasIcarus** [youzan/zent#22]
在 selection 生效的情况下需要对 disabled 的行应该在样式上加以区分..  指针样式, 文字颜色.. 

![table](http://youzan-fancy.oss-cn-shanghai.aliyuncs.com/zent-issues/zent-table.gif)

**Comment by LucasIcarus** [comment]
@linxixuan 

萌萌抽空把这个css也改了吧

**Comment by cpylua** [comment]
Examples are deprecated.
