### ISSUE TITLE
zent-tree: logic issues, some style fix

### ISSUE THREAD

**Issue by LucasIcarus** [youzan/zent#24]
1. disabled为true的节点, 是否还能打开, 以及其子节点是否还能选中
2. 为disabled节点增加一些样式以区分

![1](http://youzan-fancy.oss-cn-shanghai.aliyuncs.com/zent-issues/zent-tree-dis.gif)

3. 默认的 clone action 是否应该进行深复制

![3](http://youzan-fancy.oss-cn-shanghai.aliyuncs.com/zent-issues/zent-tree-clone.gif)

**Comment by wangchao0502** [comment]
1. 当初设计的想法时，如果数据驱动，那disabled也只控制某一个节点的行为，如果希望子节点不能被选中，需要使用者自己控制。
2. ok
3. 这个例子只做了浅拷贝，我会增加个深拷贝的例子。

我会在下周一之前更新一下例子，并优化disabled的样式

**Comment by LucasIcarus** [comment]
#81 
pre-solve

**Comment by LucasIcarus** [comment]
solved #81

**Comment by LucasIcarus** [comment]
solved #81
