### ISSUE TITLE
关于zent的文档生成

### ISSUE THREAD

**Issue by guoxiangwen** [youzan/zent#327]
请问你下关于zent的文档生成，我大概看了下zent的代码，发现site下是整个文档中心的代码，然后配置的nav导航，关联到每个component的md文档。整个文档都是侧边栏等一些组件的组合么。有没有用到什么文档发布工具之类的

**Comment by cpylua** [comment]
整个结构就是你说的那样子，你疑惑的应该是如何从 MD 文件生成页面的。

转换是通过两个 webpack loader 实现的，代码在这里[https://github.com/youzan/zent/blob/master/site/webpack/loader.config.js#L35](https://github.com/youzan/zent/blob/master/site/webpack/loader.config.js#L35)。

Loader 的代码在这里 [https://github.com/markdown-doc](https://github.com/markdown-doc)

**Comment by guoxiangwen** [comment]
哦，还有就是为啥要用pcss呢，我有个疑惑就是看你的src/component/具体的组件里面 都没有import css 是怎么应用起来的呢？

**Comment by cpylua** [comment]
1. postcss 很方便啊，为啥不用呢？
2. 样式跟 js 独立的，使用方自己引样式，或者用我们的 babel 插件自动引。

**Comment by guoxiangwen** [comment]
哦，在请教下，site里面的关联的md文件，比如Alert.md 打开后为啥还会执行alert效果呢，是怎么做到的，还有就是收起，展开代码的效果

**Comment by cpylua** [comment]
都是在上面提到的 webpack loader 里面处理的。
简单来说就是把每个 md 文件编译成了一段可执行的 js 代码。
