### ISSUE TITLE
明确浏览器支持情况

### ISSUE THREAD

**Issue by cpylua** [youzan/zent#361]
- [ ] 制定浏览器支持要求
- [ ] 改兼容性 Bug

**Comment by cpylua** [comment]
- IE >= 11 because of flex support
- Chrome ??
- Firefox
- Safari

**Comment by LucasIcarus** [comment]
http://caniuse.com/#search=flex

Click Usage re lative, then Showing all, The previous version of the one most used

**Comment by cpylua** [comment]
我们要的是支持的最低版本，你这个什么鬼...

**Comment by LucasIcarus** [comment]
真的有除了IE之外的兼容性bug嘛？  感觉用老版本chrome firefox safari 人很少啊。。
