### ISSUE TITLE
Datepicker暴露格式化字符串方法

### ISSUE THREAD

**Issue by LucasIcarus** [youzan/zent#374]
作为受控组件对Datepicker进行封装时，在手动更改value时为了一致性需要内部的格式化字符串方法，能不能作为一个函数export出来？

**Comment by xuhong** [comment]
考虑是否有必要，之前是把代码抽出来到业务组件库了，在 @youzan/utils 里面

**Comment by cpylua** [comment]
现在叫 zan-utils

**Comment by LucasIcarus** [comment]
got it
