### ISSUE TITLE
NumberInput: onChange回调函数参数不是一个标准event

### ISSUE THREAD

**Issue by wulv** [youzan/zent#392]
目前的参数`evt`只是一个简单的对象包装，在`redux-form`里面`input.onChange`可以接受`value`或者标准`event`，现在`isEvent`判断会是`false`,从而直接把`evt`当成了`value`。
`redux-form`判断是否是标准事件的依据是：
```js
  !!(evt && evt.stopPropagation && evt.preventDefault)
```
BTW:`evt.target.value`应该是`number`类型。

**Comment by cpylua** [comment]
Fixed
