### ISSUE TITLE
RangePicker2 结束时间可以小于开始时间

### ISSUE THREAD

**Issue by jinphen** [youzan/zent#424]
结束时间可以小于开始时间，如图：
![](https://img.yzcdn.cn/public_files/2017/08/15/6ab47312bd8cac9c84e140e4aa93dba3.png)

**Comment by cpylua** [comment]
这个我说一下我的理解：

打个比方，现在开始时间选了 2017-08-16, 结束时间选了 2017-08-20，然后我发现选错了月份，想改成7月份。这个时候问题来了，假如开始时间不能大于结束时间，你必须先改开始时间，再改结束时间。

反之亦然。

这种操作实际使用时很不方便的。

所以，我的建议时，使用方去做校验，比如表单提交的时候做一次校验。
