### ISSUE TITLE
Form 问题汇总贴

### ISSUE THREAD

**Issue by cpylua** [youzan/zent#442]
- [x] 文档完善：
	 * 内容比较多，我们可以考虑顶部加一个导航，便于查找
	 * 示例也要调整一下难易
- [x] 没有修改别的 Field 的方法
- [x] 提供更多表单元素组件的封装
- [x] 封装可以更进一步，提供 FormInputField 这类组件，将 Field 的包装起来，降低上手难度，现有用法依然保留。
```js
<Field
	name="name"
	type="text"
	label={"用户名："}
	component={InputField}
	helpDesc={<span>我是说明<a href="https://youzan.com">我是链接</a></span>}
	required
/>

// 重写为

<FormInputField
	name="name"
	type="text"
	label={"用户名："}
	helpDesc={<span>我是说明<a href="https://youzan.com">我是链接</a></span>}
	required
/>
```
- [x] 支持 FieldArray 和 FormSection.
- [x] isTouched/isPristine 这两个容易引起混淆，趁早改成 isDirty。
- [ ] 表单报错时支持滚动到第一个错误处

**Comment by xialvjun** [comment]
希望所有的表单组件都有个 clearable 属性，就跟 DatePicker 右边有个小叉一样。。。

这种功能非常实用，很多时候写代码时可以提供一个 defaultModel 给表单，然后用户只需要做修改就好。这种体验会好很多。。。但是如果那些表单组件不能 clearable 的话，就不能这样写了。。。

**Comment by cpylua** [comment]
Input 组件支持这个没什么问题，但是其他组件视觉上就不一定有合适的地方去放这个叉了，比如你提到的 Select，右边放个叉会很难看。

Cascader  值不能为空我们看下。

**Comment by xialvjun** [comment]
那如果觉得视觉上不大合适，可以设计个合适的方式去 clear，比如 select 可以是 clearable="请选择" 这样来增加一个空选项。。。。。。视觉上没必要完全一致。。。但是功能上还是应该要有的。。。

**Comment by cpylua** [comment]
哈哈，Select 这个可以，我们会支持的。
