### ISSUE TITLE
使用vue-cli构建的项目，不知道如何引入...

### ISSUE THREAD

**Issue by ifredom** [youzan/zent#443]
### 请认真写 Issue 的标题，会用于生成 change log。
{
  "presets": [
    ["env",{ "modules": false }],
    "stage-2"
  ],
  "plugins": [
    "transform-runtime",
    ["import", { "libraryName": "vant", "style": true }]
  ],
  "comments": false,
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": [ "istanbul" ]
    }
  }
}

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/n879nke7/).**

**What is the expected behavior?**

**Which versions of Zent and React, and which browser / OS are affected by this issue? Did this work in previous versions of Zent?**

**Comment by cpylua** [comment]
你是要用 Vue 组件库吧？
这个仓库是 React 组件库，Vue 组件库的仓库是这个：https://github.com/youzan/vant

**Comment by pangxie1991** [comment]
使用vant的话，直接安装vant依赖，在支持babel-plugin-import 情况下，可以直接通过 
```javascript
// 以 toast 为例
import { Toast } from 'vant';
```
来使用。

另外，在 [Vant 文档](https://www.youzanyun.com/zanui/vue) 上，有详细的使用姿势。如果有组件上的问题，欢迎在 [https://github.com/youzan/vant](https://github.com/youzan/vant) 上提issue

**Comment by LucasIcarus** [comment]
@pangxie1991  素质真差。
