### ISSUE TITLE
[bug fix] Select：行内元素因为font-size占据高度错误。

### ISSUE THREAD

**Issue by LucasIcarus** [youzan/zent#448]
![](http://youzan-fancy.oss-cn-shanghai.aliyuncs.com/zent-issues/17_09_07/WechatIMG209.jpeg)

![](http://youzan-fancy.oss-cn-shanghai.aliyuncs.com/zent-issues/17_09_07/WechatIMG210.jpeg)

**Comment by LucasIcarus** [comment]
resolved by #449

**Comment by cpylua** [comment]
FIXED
