### ISSUE TITLE
[bug fix] DatePicker: MonthPicker超出了最大可选置灰后仍然可选

### ISSUE THREAD

**Issue by everywill** [youzan/zent#453]
MonthPicker设置max最大可选后，虽然置灰了但仍然可选。
希望修复

另外max在文档中说明的是可选日期的最大值，实际是该日期被置灰(开区间？)，希望确认一下max属性的表现。

**Comment by xuhong** [comment]
现在是左开又闭，[min, max) ，考虑是否要换成 [min, max]，似乎这样更符合常规需求

**Comment by xuhong** [comment]
改成 [min, max] le

**Comment by cpylua** [comment]
Fixed
