### ISSUE TITLE
[new feature]Popover：组件通过onBeforeShow返回false来阻止弹窗显示

### ISSUE THREAD

**Issue by abczhijia** [youzan/zent#500]
有时候在显示一个Popover之前，我要做一个条件判断，才决定是否要显示Popover，现在的组件没有提供这个功能，只能通过visible状态来处理，觉得处理起来费事，本来内部可以独立处理的事情，非得引入一个外部状态来做。

**Comment by cpylua** [comment]
Fixed #501
