### ISSUE TITLE
只有SKU 规格选择器，没有SKU 规格显示器

### ISSUE THREAD

**Issue by Aibric** [youzan/zent#502]
为什么只有SKU 规格选择器，为什么只有没有SKU 规格显示器啊？如果有VUE版的就更好了！

**Comment by cpylua** [comment]
我们 PC 上没有用到 SKU 规格显示器，我们的组件库有 Vue 版的，里面有 SKU 组件，你可以看看。

https://www.youzanyun.com/zanui/vue#/zh-CN/component/sku

**Comment by Aibric** [comment]
其实，我的意思是有赞在添加商品的时候，在选择 SKU 规格选择器，下面有一个动态的TABLE这个组件。。。

**Comment by kylesean** [comment]
@Albric 动态table。最好实现单元格动态分组合并，我手写这个时候真的痛苦

**Comment by rainbowMorelhahahah** [comment]
> @Albric 动态table。最好实现单元格动态分组合并，我手写这个时候真的痛苦

求参考

**Comment by zaxlct** [comment]
https://github.com/zaxlct/vue-sku
用 element-ui 造了一个轮子
@Aibric

**Comment by rainbowMorelhahahah** [comment]
好 非常感谢
