### ISSUE TITLE
[bug fix] Notify: 出场动画有问题

### ISSUE THREAD

**Issue by cpylua** [youzan/zent#660]
多个实例消失的时候动画需要优化

**Comment by caiyongmin** [comment]
调整前：

<video src="http://7xrzdx.com1.z0.glb.clouddn.com/zent.mov">

**Comment by caiyongmin** [comment]
改动前的效果：

http://7xrzdx.com1.z0.glb.clouddn.com/zent.mov

改动后的效果：
