### ISSUE TITLE
没有vue么....

### ISSUE THREAD

**Issue by a5108** [youzan/zent#681]
我要VUE.....

**Comment by cpylua** [comment]
https://www.youzanyun.com/zanui/vant

**Comment by Tinysymphony** [comment]
@a5108  https://github.com/youzan/vant   这个才是vue

**Comment by CharlesSong** [comment]
但是想在Vue项目中使用ZanUI的微页面编辑器、规格选择器

**Comment by zhangdaren** [comment]
我也有这个需求啊

**Comment by zaxlct** [comment]
@CharlesSong 
@zhangdaren 
@psr4 
https://zaxlct.github.io/vue-sku/
用 element-ui 谢了一个例子。。。

**Comment by strengthCAT** [comment]
> 但是想在Vue项目中使用ZanUI的微页面编辑器、规格选择器

同想
