### ISSUE TITLE
考虑 extends Component 而不是 PureComponent

### ISSUE THREAD

**Issue by thoamsy** [youzan/zent#715]
# [bug fix] 大量的 PureComponent 不一定是好的
我发现 zent 中大量的组件 extends `PureComponent`，甚至这个组件明明可以写成 **stateless component**, 比如 [Card](https://github.com/youzan/zent/blob/master/packages/zent/src/card/Card.js)

这里有一篇[卓越的文章](https://cdb.reacttraining.com/react-inline-functions-and-performance-bdff784f5578) 描述了关于 `PureComponent` 的问题. 
大概意思就是如果某个组件,
它的某个 `props` 使用了内联的方式, 但是这个 props 刚好又不是**原始类型**, 这样每次 `render` 肯定都会带来 reconciliation. 
相比普通的 `Component`, 只 diff 一次就可以确定需要 update, 而使用 PureComponent 反而还需要 diff 两次. 

```js
<B>
  <A style={{color: 'red'}} />
</B>
```
如果 A 是 `PureComponent` 的话, 那么每次 render B 都会导致这个问题,

所以除非能保证使用的时候, 每次都是传递变量名而不是内联的话, PureComponent 也没什么问题. 但是, 作为一个开源框架应该很难保证这种情况的发生吧😂

当然, 如果一个组件的 props 都是**原始类型**的话, 确实可以考虑使用 PureComponent, 不过这种情况下应该就是一个单纯的 Presentational Component，可能还不如使用 Stateless Component 的效果好。
## 结论
引用文章作者的一段话：
> There are no silver bullets when it comes to performance. You have to measure.

所以在采纳我的建议之前, 可以测试一下 PureComponent 是否真的给性能带来了提升.

**Comment by cpylua** [comment]
逐个回答你的问题：

1. 组件库里所有导出的组件都**不能**是 Functional component，因为不能往上加 `ref`，我们没法保证所有用户都不会往上加 `ref`，所以 Card 组件不会写成 Functional component。

2. 关于 PureComponent，我同意你的观点，there's no silver bullets。我们希望解决的场景是上层刷新了，下层组件没变化的时候不去render。就像你说的不管选哪种都不能解决所有问题，我们想解决的仅仅是这个场景而已。我明白这个决定不是所有人都满意，但现状是必须做个决定。

另外， `shouldComponentUpdate` 里的浅比较开销远比组件树的 `diff` 小，你发的那篇文章把两个 diff 混为一谈，我个人不是很认同。

```
class App extends React.Component {
	static propTypes = {
  	name: PropTypes.string,
  };
  
  state = {
  	count: 1
  };
  
  render() {
  	return (
    	<div>
    	  <h1>Hello, {this.props.name} {this.state.count}</h1>
        <button onClick={() => {this.setState(state => ({count: state.count+1}))}}>click</button>
        <Inner />
        <InnerPure />
    	</div>
    );
  }
}

class Inner extends React.Component {
	render() {
  	console.log('render');
  	return 'inner, ';
  }
  
  shouldComponentUpdate() {
  	console.log('should component update');
    return true;
  }
}

class InnerPure extends React.PureComponent {
	render() {
    console.log('pure render');
  	return 'inner pure';
  }
}

ReactDOM.render(<App name="world"/>, document.getElementById('container'));
```

**Comment by thoamsy** [comment]
怎么说呢. 你的样例代码和我描述的这个场景有点不同.
虽然你的这个场景也是一个痛点, 不过和原文中的场景比起来时候更值得关注呢? 这个不好下定论
原文中说到的是, 如果在 `PureComponent` 中的某个 props 出现内联. 
这种情况下, 无论 `Component` 还是 `PureComponent` 都会 reconciliation, 并确定需要进行一次 update 对吧. 那么, 显然 PureComponent 多进行了一次针对 state 的 diff.

如果上面的代码改成
```js
iimport React, { Component, PureComponent } from 'react';
import ReactDOM from 'react-dom';
import PropTypes from 'prop-types';
class App extends Component {
  static propTypes = {
    name: PropTypes.string,
  };

  state = {
    count: 1,
  };

  render() {
    return (
      <div>
        <h1>
          Hello, {this.props.name} {this.state.count}
        </h1>
        <button
          onClick={() => {
            this.setState(state => ({ count: state.count + 1 }));
          }}>
          click
        </button>
        <Inner foo={() => { }}/>
        <InnerPure foo={() => { }}/>
      </div>
    );
  }
}

class Inner extends Component {
  render() {
    console.log('render');
    return 'inner, ';
  }

  componentDidUpdate() {
    console.log('I also update!');
  }
}

class InnerPure extends PureComponent {
  componentDidUpdate() {
    console.log('I am update!');
  }
  render() {
    console.log('pure render');
    return 'inner pure';
  }
}

ReactDOM.render(<App name="world" />, document.getElementById('container'));

```
那么这种情况下 PureComponent 就没有起到任何用处了. 因为不能保证没有人不内联 PureComponent 的  props 吧.

另外, 这个[讨论](https://news.ycombinator.com/item?id=14418576) 描述了这个问题, 可以看看

**Comment by thoamsy** [comment]
`ref` 的问题, 不知道可不可以尝试这种方式 😂
```js
import React from 'react';
const Card = () => {
  let aha = null;
  return (
    <input ref={node => aha = node} onChange={() => console.log(aha.value)} />
  );
};
export default Card;
```
使用闭包来取到 ref, 不知道这种方式对你们的场景时候适用

**Comment by cpylua** [comment]
我说的是在Card上加ref，咱两说的不是一个事。

PureComponent这事我觉得没必要揪着一个点，不管用PureComponent还是Component都有痛点。你例子里的用法不是我们的推荐用法，你说的style那种场景在我们组件库里出现不多。所以结论我已经说了，我们的选择就是PureComponent。

没有必要在这事上太过纠结，这点性能一般不会是瓶颈。
