### ISSUE TITLE
Upload: 增加上传不限制文件类型的支持

### ISSUE THREAD

**Issue by huangsy** [youzan/zent#730]
- 现在上传组件只能上传图片和音频文件，希望能加上任意类型文件上传的支持

**Comment by lk1583880553** [comment]
![image](https://user-images.githubusercontent.com/39514393/56724210-20c70e80-677d-11e9-9012-65e75d757d08.png)
upload底层封装有支持video文件类型的
zent版本号（"zent": "^6.6.2"）

**Comment by lk1583880553** [comment]
如果你还想支持其他类型，比如.doc，.voice等类型，可以自行修改moudel中ts文件

**Comment by cpylua** [comment]
新版已支持
