### ISSUE TITLE
[bug fix] Select: 标签选择时placeholder缩进不一致

### ISSUE THREAD

**Issue by linrz** [youzan/zent#747]
如下图所示，在同一表单中使用感知较为明显
![wechatimg22](https://user-images.githubusercontent.com/33575974/36524398-d02cfd14-17e0-11e8-8397-519a390a3b8c.jpeg)
![wechatimg594](https://user-images.githubusercontent.com/33575974/36524448-010e26ce-17e1-11e8-9f47-f6961f86c447.jpeg)

**Comment by lama-pacos** [comment]
+1

**Comment by cpylua** [comment]
Fixed
