### ISSUE TITLE
[bug fix]zan-design的cubeConf,navConf出现空白

### ISSUE THREAD

**Issue by Lanceloft** [youzan/zent#777]
已经和其他组件引入方式相同，
cubeConf，navConf点击会重新请求bundle.js并出现空白
[图片](http://og683rb19.bkt.clouddn.com/cube.png)

**Comment by cpylua** [comment]
**抱歉，`zan-design` 这个包仅做我们网站演示用途，你可以使用，但我们不提供技术支持。**

Zent 的 `Design` 组件里有如何实现自己的 `Design` 组件的例子，可以参考[这个目录下的组件代码](https://github.com/youzan/zent/tree/master/packages/zent/src/design/components)。建议自己实现需要的组件。

顺带说一句，你图上的问题是因为少了 `react-dnd` 的 [context](http://react-dnd.github.io/react-dnd/docs-drag-drop-context-provider.html)。

**Comment by aiqin-bao** [comment]
![image](https://user-images.githubusercontent.com/23024047/61203948-6cef7280-a71e-11e9-994d-6cefe83769dc.png)
 链接打不开~~
