### ISSUE TITLE
是否有design组件保存草稿方法

### ISSUE THREAD

**Issue by Lanceloft** [youzan/zent#786]
看到官网demo和example都没有提供design组件里面保存草稿的功能.
关于这一块功能请问是如何进行解决.看到有赞商城是采取讲组件的值进行保存
想问个各个组件的状态从哪个属性可以获取?

**Comment by cpylua** [comment]
`Design` 的值就是你传进去的 `value`，所以不存在从哪里取的问题。值有了如何实现草稿功能那是业务逻辑了，你可以根据自己的需要在服务器端实现。

**Comment by Lanceloft** [comment]
看到localstorage里面有添加的组件的状态保存, 请问这个状态是在哪里获取到.从this里面没有找到想要的内容

**Comment by cpylua** [comment]
这是组件私有的，使用者不应该依赖实现细节。你要定制缓存逻辑可以禁用组件自带的逻辑，自己实现。

**Comment by Lanceloft** [comment]
想根据现有方法进行使用,就不需要禁用自带逻辑.当然自己实现是好方法, 但是还是想参考原本组件方法.

**Comment by Lanceloft** [comment]
已找到,this.state.value 中可以获取编辑内容
