### ISSUE TITLE
React 16.3.2 Loading设置为float后无法关闭

### ISSUE THREAD

**Issue by EleanorMao** [youzan/zent#822]
# React 16.3.2 Loading设置为float后无法关闭

说明：
React版本16.3.2，使用<Loading  float  show={this.state.show} />，Loading无法关闭。
查看源码之后发现是因为使用ReactDOM.render获取Loading的实例，但是ReactDOM16无法获取stateless组件的实例。
另外鉴于zent只兼容React >= 15.6，为什么不使用createPortal，
或者如果仍然要保持这种方式的话，建议可以在Loading中新建一个回调，return出实例

**Comment by cpylua** [comment]
请给一个可以重现的 demo。

1. 跟 stateless 没关系，loading 不是 stateless 的。
2. 15 没有 portal。

**Comment by EleanorMao** [comment]
我提交了一个PR。
关于ReactDOM在16之后不会返回实例的说明，请看[这里](https://reactjs.org/docs/react-dom.html#render)

关于demo，只要React是16+就可以重现了，本地跑dev就可以看到了。

**Comment by EleanorMao** [comment]
[code](https://github.com/EleanorMao/zent-loading-demo)
[live demo](http://chashaobao.net/zent-loading-demo/)
