### ISSUE TITLE
form的一些问题

### ISSUE THREAD

**Issue by geminiwen** [youzan/zent#83]
1. form 的 onSubmit 校验不支持一个key对应多value的情况
2. form 无法使用同步提交

是我没有找到 API么？

**Comment by cpylua** [comment]
没明白你的意思，方便的话贴个示例

1. 一个`key`对应多个`value`是什么意思？
2. 同步提交你指的是`<form action="url"></form>`？

**Comment by geminiwen** [comment]
1. 是指 querystring key=v1&key=v2&key=v3 此类的场景
2. 没错，multipart，好像Form没有暴露其他的字段。
我想问下怎么用

**Comment by cpylua** [comment]
听你的描述，我推荐你直接用原生的form标签。我们组件库里的Form组件更适合通过js提交的表单场景。

至于第一个问题，js可以用数组来达到你的需求。querystring跟组件无关，那是网络请求序列化该处理的事。
