### ISSUE TITLE
下拉框样式问题

### ISSUE THREAD

**Issue by cpylua** [youzan/zent#884]
级联下拉框和普通下拉框，三角的颜色和样式不同；
有些地方的三角是灰色，应该都是333333的色值才对

![image](https://user-images.githubusercontent.com/726800/42266470-13cfc814-7fa9-11e8-9d10-4c2b23d8b1a2.png)

**Comment by NinoFocus** [comment]
- 下拉箭头大小不一致
- 下拉箭头距离输入框右边的边框距离不一致
