### ISSUE TITLE
[bug fix]DatePicker: 关闭autoComplete提示

### ISSUE THREAD

**Issue by zedmund** [youzan/zent#886]
DatePicker默认没有关闭autoComplete，Chrome浏览器下focus后有浏览器自带提示，且点击提示下拉框内的值组件并不会更新。
![image](https://user-images.githubusercontent.com/9364801/42669244-f5288920-8686-11e8-9d17-0894ff75f84b.png)

**Comment by nodew** [comment]
#918 已修复
