### ISSUE TITLE
[bug fix] Form: FieldArray 新增子元素异常

### ISSUE THREAD

**Issue by wolfdu** [youzan/zent#891]
以文档中展示demo内容为例：
填入成员1信息：
![image](https://user-images.githubusercontent.com/22972582/42862472-303eac6a-8a92-11e8-937c-1c6fea05a06b.png)

然后添加下一个成员信息出现异常：
![image](https://user-images.githubusercontent.com/22972582/42862491-4edbc3c4-8a92-11e8-82a3-b7a5cd34e46a.png)

**Comment by elvin-gogo** [comment]
同问
