### ISSUE TITLE
[bug fix] 官网demo部分组件运行报错

### ISSUE THREAD

**Issue by PENG199** [youzan/zent#894]
demo部分组件运行报错，如图。
![image](https://user-images.githubusercontent.com/12715867/42924196-94cf1fce-8b5b-11e8-8c6c-8887efb5f2d3.png)

**Comment by cpylua** [comment]
用 yarn 安装依赖试试，yarn 应该是锁版本了。

新版组件使用上有些区别。

**Comment by PENG199** [comment]
好的，通过yarn安装后可以使用了，demo的README中说里面的组件放在Zent中了，但是并没有在zent中看到demo中的那些组件。只有少数几个。

**Comment by cpylua** [comment]
Design 的组件我们不提供，需要自己实现，demo 只是示例。
