### ISSUE TITLE
Gutter for zent layout

### ISSUE THREAD

**Issue by therealedsheenan** [youzan/zent#899]
**Do you want to request a *feature* or report a *bug*?**
The current Layout component doesn't support gutter on `Row` and `Col`.
Is there any way to create this?

**Comment by cpylua** [comment]
hi @therealedsheenan there's no way to create gutters. We're redesigning the `Layout` component, gutter will be supported in the upcoming version.

**Comment by therealedsheenan** [comment]
If there is anything I could help, please tag me along! Would love to help you guys.

**Comment by cpylua** [comment]
Fixed in #997
