### ISSUE TITLE
[new feature] NumberInput：应该在onchange事件的event中告知引起onchange的原因（min，max，value等）

### ISSUE THREAD

**Issue by sxq111** [youzan/zent#910]
应该在onchange事件的event中告知引起onchange的原因（min，max，value等）

**Comment by cpylua** [comment]
请问使用场景是什么？

**Comment by sxq111** [comment]
零售pc的一个场景，主动退款时，有一个numberinput
![image](https://user-images.githubusercontent.com/5954146/44511299-a32c9980-a6e9-11e8-8507-14a68abf2591.png)
这个表单很简单，没有使用createform，校验就写在了input的onChange里
然后它的max和min通过ajax获取，然后导致了它的onchange触发。
最后结果就是用户一打开页面，就显示输入不能为空

**Comment by intellild** [comment]
#1025
