### ISSUE TITLE
微页面编辑里面的富文本可否开源～  react结合ueditor还是非常完美的～～

### ISSUE THREAD

**Issue by aiqin-bao** [youzan/zent#916]
在做后台的同时，结合富文本编辑的需求还是满多的～ 手动改过ueditor的源码～ 结合react的契合度及设计还是感觉你们的比较好～ 希望可以借鉴一下  能否开源 谢谢

**Comment by cpylua** [comment]
直接使用 ueditor 即可，我们只是在上面封装了非常简单的一层，让它能比较方便的在 React 下工作。

代码不便公开，涉及业务。

**Comment by YaoKaiLun** [comment]
目前 editor 支持异步加载数据进行初始化吗？
