### ISSUE TITLE
[bug fix] form 下 FormNumberInputField disabled 属性设置为 true 会造成 Maximum update depth exceeded 错误

### ISSUE THREAD

**Issue by foreverzmy** [youzan/zent#930]
[bug fix] form 下 FormNumberInputField disabled 属性设置为 true 会造成 Maximum update depth exceeded 错误

![image](https://user-images.githubusercontent.com/11779129/45023641-82f5c680-b069-11e8-9cff-c0e2207a0d6a.png)

**Comment by cpylua** [comment]
给个可以复现的例子

**Comment by cpylua** [comment]
无法复现
