### ISSUE TITLE
previewImage 点击背景无法关闭

### ISSUE THREAD

**Issue by lingjieee** [youzan/zent#934]
import {previewImage} from 'zent';
使用这种方式引入时：点击背景区域可以正常关闭图片
import previewImage from 'zent/lib/preview-image';
使用这种方式时，点击背景区域无反应，但如果这是使用了babel-plugin-zent插件，则又正常了

**Comment by cpylua** [comment]
看下样式有没有引入

**Comment by lingjieee** [comment]
样式引入是正常的

**Comment by cpylua** [comment]
无法复现
