### ISSUE TITLE
[bug]SKU组件在antd的modal中使用时，选择sku项出错

### ISSUE THREAD

**Issue by tourze** [youzan/zent#964]
![image](https://user-images.githubusercontent.com/13899502/48967975-8cb51780-f023-11e8-8a6c-0f164f45d7fb.png)
如果，此时点击选项是无效的。

代码：
![image](https://user-images.githubusercontent.com/13899502/48967980-a5bdc880-f023-11e8-906d-f976b695abad.png)

**Comment by javrven** [comment]
确认框样式的问题。z-index比较小，被你的modal遮住了

**Comment by tourze** [comment]
> 确认框样式的问题。z-index比较小，被你的modal遮住了

确认是这个问题。谢谢啦
