### ISSUE TITLE
New design - style update

### ISSUE THREAD

**Issue by cpylua** [youzan/zent#968]
Update styles for these components with a few new features.

- [x] Button
- [x] SplitButton
- [x] Breadcrumb
- [x] Steps
- [x] Menu
- [x] Radio
- [x] Checkbox
- [x] Input
- [x] Select
- [x] Slider
- [x] Switch
- [x] Badge
- [x] Collapse
- [x] Pop
- [x] Tabs
- [x] Tag
- [x] Timeline
- [x] Dialog
- [x] Progress
- [x] Rate

Rewrite:

- [x] Pagination
- [x] Layout

**Comment by chanjsq** [comment]
Hi, what's the progress now?

**Comment by cpylua** [comment]
We are working on branch `new-theme`.
