### ISSUE TITLE
Select Search 组件 focus 错误

### ISSUE THREAD

**Issue by youngBrain1893** [youzan/zent#978]
[bug fix] Select：Select Search 组件 focus 错误

说明：
![image](https://user-images.githubusercontent.com/16771528/50090100-8b51c600-0242-11e9-8660-ea36973c64ed.png)

**What is the current behavior?**
有时 Select 组件会抛 `Cannot read property 'focus' of null`

**Comment by cpylua** [comment]
Fixed in #979
