### ISSUE TITLE
Grid: `Cannot read property 'getBoundingClientRect' of null` in Grid. syncFixedTableRowHeight 

### ISSUE THREAD

**Issue by nodew** [youzan/zent#987]
In a specific case, the Grid component will trigger an error as what the title said. the debounce function will delay the execution of syncFixedTableRowHeight method. If the Grid is destroyed, the table node ref will be null, and then the syncFixedTableRowHeight method will throw the error.

https://github.com/youzan/zent/blob/22bcb3bc694a3d992e2e02b9e2644ad907416ebb/packages/zent/src/grid/Grid.js#L778

https://github.com/youzan/zent/blob/22bcb3bc694a3d992e2e02b9e2644ad907416ebb/packages/zent/src/grid/Grid.js#L119

**Comment by cpylua** [comment]
Fixed #990
